# Generated by Django 6.0.1 on 2026-06-12 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('access_hours', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('mercado_pago_payment_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('external_reference', models.CharField(max_length=80, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('access_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de contribuicao',
                'verbose_name_plural': 'Pagamentos de contribuicao',
                'ordering': ['-created_at'],
            },
        ),
    ]
