# Generated by Django 6.0.1 on 2026-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='musical_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='musical_genre',
            field=models.ManyToManyField(blank=True, to='accounts.musicalgenre', verbose_name='Gêneros musicais favoritos'),
        ),
    ]
