# Generated by Django 6.0.1 on 2026-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_musical_genre_user_musical_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('acessos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-acessos'],
            },
        ),
    ]
