# Generated by Django 6.0.1 on 2026-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_musicaestatistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='username'),
        ),
    ]
