# Generated by Django 6.0.1 on 2026-06-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Karaoke do Cowboy', max_length=120)),
                ('hero_subtitle', models.CharField(default='As 3 mais pedidas do saloon -- bora cantar!', max_length=180)),
                ('allow_registration', models.BooleanField(default=True)),
                ('maintenance_message', models.CharField(blank=True, max_length=220)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao do site',
                'verbose_name_plural': 'Configuracoes do site',
            },
        ),
    ]
