# Generated by Django 6.0.1 on 2026-06-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessao de convidado',
                'verbose_name_plural': 'Sessoes de convidados',
            },
        ),
        migrations.CreateModel(
            name='GuestPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('artista', models.CharField(blank=True, max_length=200)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='accounts.guestsession')),
            ],
            options={
                'verbose_name': 'Musica de convidado',
                'verbose_name_plural': 'Musicas de convidados',
                'ordering': ['-played_at'],
                'unique_together': {('guest', 'codigo')},
            },
        ),
    ]
