# Generated by Django 6.0.1 on 2026-06-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guestsession_guestplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_released',
            field=models.BooleanField(default=False, verbose_name='Acesso liberado pelo admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='song_limit',
            field=models.PositiveIntegerField(default=2, verbose_name='Limite inicial de musicas'),
        ),
        migrations.CreateModel(
            name='UserPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('artista', models.CharField(blank=True, max_length=200)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musica cantada por usuario',
                'verbose_name_plural': 'Musicas cantadas por usuarios',
                'ordering': ['-played_at'],
                'unique_together': {('user', 'codigo')},
            },
        ),
        migrations.DeleteModel(
            name='GuestPlay',
        ),
        migrations.DeleteModel(
            name='GuestSession',
        ),
    ]
