# Generated by Django 6.0.1 on 2026-06-12 22:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_access_released_user_song_limit_userplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='paid_access_hours',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acesso pago expira em'),
        ),
    ]
