# Generated by Django 6.0.1 on 2026-06-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_siteconfiguration_contribution_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login com sucesso'), ('login_failure', 'Falha de login'), ('logout', 'Logout'), ('list_view', 'Tela de busca'), ('music_detail', 'Detalhe da musica'), ('music_play', 'Musica iniciada'), ('video_watch', 'Tempo de visualizacao')], max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('artista', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='accounts_au_event_t_13ec89_idx'), models.Index(fields=['codigo', '-created_at'], name='accounts_au_codigo_c44981_idx')],
            },
        ),
    ]
